### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by SomethingStillWrong** [ff98sha/mclangcn#103]
加载包后，设置内的语言界面的中文（简体）应该为简体中文（中国大陆），和Java版进行统一
![屏幕截图 2024-09-13 211923](https://github.com/user-attachments/assets/b63a590f-a12e-49d5-a6c7-c302285dc588)
可通过游戏内对language_names.json的修改而实现。
![屏幕截图 2024-09-13 211957](https://github.com/user-attachments/assets/dd2fa66b-0936-4371-8512-d47e66858700)

**Comment by ff98sha** [comment]
此处与基岩版统一
