### ISSUE TITLE
教育版使用译名修正包在睡觉的时候聊天栏不会显示玩家睡觉数量

### ISSUE THREAD

**Issue by JYN2018X** [ff98sha/mclangcn#80]
教育版使用译名修正包在睡觉的时候聊天栏不会显示玩家睡觉数量，版本1.20.12，可能需要修改

**Comment by SomethingWasWrong-David** [comment]
能发图看下吗

**Comment by JYN2018X** [comment]
> 能发图看下吗

这个，因为教育版版本是1.20.12，然后会显示“XXX正在床上睡觉。要快进到黎明，还需要%s名玩家同时在床上睡觉。”，因为没有加入那个睡眠调整制度，所以会直接%s

**Comment by SomethingWasWrong-David** [comment]
睡眠调整，是不是playersleepingpercentage？若你描述是这个，那么它在1.20.30加入，而教育版只同步至1.20.12。
