### ISSUE TITLE
添加有关使用表情时聊天显示的译名

### ISSUE THREAD

**Issue by JYN2018X** [ff98sha/mclangcn#82]
persona.emote.chatMessage=@ 在&挥手&。	#
persona.emote.chatMessageEasterEgg=@ 的胳膊因为不停地&挥手&而疲惫不堪。	#
persona.emote.chatMessage=@ 在&鼓掌&。	#
persona.emote.chatMessageEasterEgg=@：恭喜！	#
persona.emote.chatMessage=@ 正指向&那边&！	#
persona.emote.chatMessageEasterEgg=@：这不起作用...苦力怕！	#
persona.emote.chatMessage=@ 要求大家&跟随&。	#
persona.emote.chatMessageEasterEgg=@：羊驼火车，出发！（&跟随&）	#
上面的这些翻译情纠正

**Comment by OregonBanner** [comment]
使用部分动作时聊天框所发送的提示，这也包括彩蛋

获取Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
发件人: SomethingWrong ***@***.***>
发送时间: 星期三, 十月 4, 2023 12:30:22 上午
收件人: ff98sha/mclangcn ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ff98sha/mclangcn] 添加有关使用表情时聊天显示的译名 (Issue #82)


这些是在哪里的

―

**Comment by SomethingWasWrong-David** [comment]
OK

**Comment by SomethingWasWrong-David** [comment]
这些在哪个文件夹内

**Comment by Jingji132** [comment]
这些文本使用了相同的键，常规情况下无法同时修改

**Comment by SomethingWasWrong-David** [comment]
可以參考我的項目，把鍵名修改

**Comment by SomethingWasWrong-David** [comment]
而且这些还是个文件夹内的文件夹内....
