### ISSUE TITLE
游戏指南中使用了错误的译名

### ISSUE THREAD

**Issue by Bannedfail** [ff98sha/mclangcn#89]
![Screenshot_20240203_200426](https://github.com/ff98sha/mclangcn/assets/158742863/427b85ff-809a-4b88-be4b-1a2190fc8a5b)
此处的“护盾”应为“盾牌”。

**Comment by Bannedfail** [comment]
这句话的本地化键名是`howtoplay.armor.text.5b.touch`

**Comment by Andypsl8** [comment]
问题已创建，见 https://zh.crowdin.com/editor/mclangcn/59/en-zhcn?view=comfortable#325503

**Comment by Jingji132** [comment]
将在下一次发布时解决此问题
