### ISSUE TITLE
游戏指南有一处语法错误

### ISSUE THREAD

**Issue by LinmuRen** [ff98sha/mclangcn#91]
游戏指南>游戏百科>主世界 村民交易 中存在一处语法错误。参考下图：
![Screenshot_20240219_101515_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/ff98sha/mclangcn/assets/111480168/b67e5942-abd0-442a-b3cd-ece445e6b7b7)
若无法查看图片，请参照以下文段（取自原文）：
“……村民可能会缺货，或者由于过于频繁地使用某项交易从而导致其暂时被禁用。交易通常**涉及到**绿宝石的交换。”
其中“涉及到”的用法是错误的，应改为“涉及”。

**Comment by SomethingWasWrong-David** [comment]
已提交，详情在这[这](https://zh.crowdin.com/editor/mclangcn/all/en-zhcn?view=comfortable&filter=basic&value=0#q=%E6%9D%91%E6%B0%91%E5%8F%AF%E8%83%BD%E4%BC%9A%E7%BC%BA%E8%B4%A7%EF%BC%8C%E6%88%96%E8%80%85%E7%94%B1%E4%BA%8E%E8%BF%87%E4%BA%8E%E9%A2%91%E7%B9%81%E5%9C%B0%E4%BD%BF%E7%94%A8%E6%9F%90%E9%A1%B9%E4%BA%A4%E6%98%93%E4%BB%8E%E8%80%8C%E5%AF%BC%E8%87%B4%E5%85%B6%E6%9A%82%E6%97%B6%E8%A2%AB%E7%A6%81%E7%94%A8%E3%80%82%E4%BA%A4%E6%98%93%E9%80%9A%E5%B8%B8%E6%B6%89%E5%8F%8A%E5%88%B0%E7%BB%BF%E5%AE%9D%E7%9F%B3%E7%9A%84%E4%BA%A4%E6%8D%A2%E3%80%82)

**Comment by ff98sha** [comment]
solved in #94
