### ISSUE TITLE
游戏指南有几处错误：

### ISSUE THREAD

**Issue by LinmuRen** [ff98sha/mclangcn#92]
![Screenshot_20240223_150225_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/ff98sha/mclangcn/assets/111480168/51878934-7eef-4612-b6ed-762147e7b3bc)
以下文段（取自原文）：
“你几乎可以不受限制的创造一切事物！”
其中“不受限制的”应作“不受限制地”；
“大多数方块不受重力影响，可以漂浮在半空；但像沙子和砂砾之类的物品将会落
下(如果下方没有方块)。”
其中存在3处错误：
1. “漂浮”应作“飘浮”；
2. 根据译名标准化，“砂砾”应作“沙砾”；
3. “物品”应为“方块”（说成“物品”可能存在歧义）。

**Comment by LinmuRen** [comment]
还有，“你几乎可以不受限制的创造一切事物”中“不受限制的”应作“不受限制地”。

**Comment by SomethingWasWrong-David** [comment]
你好，关于第一个问题，我已提交，见[此](https://crowdin.com/editor/mclangcn/all/en-zhcn?view=comfortable&filter=basic&value=0#q=%E6%B2%99%E5%AD%90%E5%92%8C%E6%B2%99%E7%A0%BE)
后面两个问题已在Crowdin那边修复。

**Comment by ff98sha** [comment]
solved in #94
